name: Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up
        uses: ./.github/actions/setup
      - name: Validate image thumbnails
        run: |
          bin/validate-thumbnails

permissions:
  contents: write
